# Generated by Django 3.2.4 on 2021-06-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0002_auto_20210612_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='owner',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='username',
            field=models.CharField(default='Anonimo', max_length=1024),
        ),
    ]
